export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';

export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';

export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';




